version: '3.8'

services:
  mongo:
    build: ./mongodb-rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: '27017'
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
